### ISSUE TITLE
Problem when loading a GameTurn with a previousGameTurn field set.

### ISSUE THREAD

**Issue by mcybulsk** [civ5-pbem/civ5-pbem-server#20]
Stacktrace:
```
2017-12-26 14:55:14.672 ERROR 4355 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: HHH000142: Bytecode enhancement failed: me.cybulski.civ5pbemserver.game.GameTurn; nested exception is org.hibernate.HibernateException: HHH000142: Bytecode enhancement failed: me.cybulski.civ5pbemserver.game.GameTurn] with root cause

java.lang.NoSuchMethodException: me.cybulski.civ5pbemserver.game.GameTurn_$$_jvsted6_0.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_144]
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.getProxy(JavassistProxyFactory.java:125) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.createProxy(AbstractEntityTuplizer.java:761) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.createProxy(AbstractEntityPersister.java:4595) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.createProxyIfNecessary(DefaultLoadEventListener.java:359) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:274) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1239) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1122) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:646) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:431) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:165) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:125) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.performTwoPhaseLoad(AbstractRowReader.java:238) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:209) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:133) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:122) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:86) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.load(AbstractLoadPlanBasedEntityLoader.java:167) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4083) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:508) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:478) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:219) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:278) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1239) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1122) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:646) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:431) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:165) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:125) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1152) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:1011) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:949) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2692) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2675) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2502) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:384) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1490) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445) ~[hibernate-core-5.2.12.Final.jar:5.2.12.Final]
```

**Comment by mcybulsk** [comment]
Workaround from StackOverflow: https://stackoverflow.com/a/7373445

**Comment by mcybulsk** [comment]
Temporary fix merged with master.
