### ISSUE TITLE
Internal Server Error upon uploading a non-save file

### ISSUE THREAD

**Issue by k-cybulski** [civ5-pbem/civ5-pbem-server#46]
When a non-save file is uploaded to the server in place of a correct save file, the server returns a `500` `Internal Server Error` with a message `Java heap space` which is not a very descriptive response. Maybe caused by a server-side parser error?

**Comment by mcybulsk** [comment]
When system is low on memory you can get:
```
java.lang.OutOfMemoryError: Java heap space
        at me.cybulski.civ5pbemserver.savegame.SaveGameParser.readString(SaveGameParser.java:105) ~[classes!/:na]
        at me.cybulski.civ5pbemserver.savegame.SaveGameParser.parse(SaveGameParser.java:36) ~[classes!/:na]
        at me.cybulski.civ5pbemserver.game.SaveGameSynchronizer.synchronizeDeadPlayers(SaveGameSynchronizer.java:26) ~[classes!/:na]
        at me.cybulski.civ5pbemserver.game.GameApplicationService.finishTurn(GameApplicationService.java:173) ~[classes!/:na]
        at me.cybulski.civ5pbemserver.game.GameApplicationService$$FastClassBySpringCGLIB$$5dab6e31.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$587/123221411.proceedWithInvocation(Unknown Source) ~[na:na]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at me.cybulski.civ5pbemserver.game.GameApplicationService$$EnhancerBySpringCGLIB$$67ac1f37.finishTurn(<generated>) ~[classes!/:na]
        at me.cybulski.civ5pbemserver.game.GamesController.finishTurn(GamesController.java:86) ~[classes!/:na]
        at sun.reflect.GeneratedMethodAccessor321.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.23.jar!/:8.5.23]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855) ~[spring-webmvc-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.23.jar!/:8.5.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.23.jar!/:8.5.23]
```

**Comment by mcybulsk** [comment]
Fixed
